import './globals.css'

export const metadata = {
  title: 'Github Projects',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="pt-br">
      <body>
        <div className='container'>
          {children}
        </div>
      </body>
    </html>
  )
}
