import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"

export const metadata = {
    title: 'Github Projects',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>

    )
}
